const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const PAGE = {
  margin: 40,
  contentWidth: 515
};
const FOOTER_HEIGHT = 86;

const COLORS = {
  brandBlue: '#0f4f98',
  brandBlueDark: '#0b2f62',
  brandBlueSoft: '#eaf3ff',
  brandLine: '#8db5db',
  text: '#10243f',
  textMuted: '#4f6780',
  white: '#ffffff',
  tableHeaderText: '#ffffff',
  rowAlt: '#f6faff',
  blockBg: '#f1f7ff'
};

const DEFAULT_ORG_ADDRESS =
  '302, Sangini Aspire, Beside Sanskruti Township Near Pal RTO, Pal-Hajira Road, Pal Gam, Surat, Gujarat - 395009';

const DIGITAL_DECLARATION_DEFAULT =
  'This Minutes of Meeting (M.O.M) is a digitally generated record of meeting discussions and outcomes. It is produced from system-captured inputs and therefore does not require a handwritten signature for verification.';

const LOGO_PATH = path.join(__dirname, '..', 'public', 'assets', 'elegrow-logo-full.png');

function safeText(value) {
  if (value === undefined || value === null || value === '') {
    return '-';
  }
  return String(value);
}

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function generateFileName() {
  const stamp = new Date().toISOString().replace(/[.:]/g, '-');
  return `MOM-${stamp}.pdf`;
}

function normalizeProjectNumber(value) {
  const text = String(value || '').trim();
  if (!text) {
    return '-';
  }
  return text.split('/')[0].trim() || text;
}

function ensurePageSpace(doc, requiredHeight = 80, authenticity = null) {
  const usableBottom = doc.page.height - doc.page.margins.bottom - FOOTER_HEIGHT;
  if (doc.y + requiredHeight > usableBottom) {
    doc.addPage();
    if (authenticity) {
      drawPageHeader(doc, authenticity);
    } else {
      drawHeaderBarOnly(doc);
    }
  }
}

function drawHeaderBarOnly(doc) {
  const x = PAGE.margin;
  const y = PAGE.margin - 2;
  doc
    .moveTo(x, y)
    .lineTo(x + PAGE.contentWidth, y)
    .lineWidth(2.2)
    .strokeColor(COLORS.brandBlue)
    .stroke();
}

function drawPageHeader(doc, authenticity = {}) {
  const x = PAGE.margin;
  const y = 20;
  const rightWidth = 250;

  if (fs.existsSync(LOGO_PATH)) {
    doc.image(LOGO_PATH, x, y, { fit: [220, 52], align: 'left', valign: 'top' });
  }

  doc
    .font('Helvetica')
    .fontSize(8.8)
    .fillColor(COLORS.textMuted)
    .text(`Document ID: ${safeText(authenticity.documentId)}`, x + PAGE.contentWidth - rightWidth, y + 4, {
      width: rightWidth,
      align: 'right'
    })
    .text(`Generated: ${safeText(authenticity.generatedAt)}`, x + PAGE.contentWidth - rightWidth, y + 18, {
      width: rightWidth,
      align: 'right'
    })
    .text(`Generated by: ${safeText(authenticity.generatedBy)}`, x + PAGE.contentWidth - rightWidth, y + 32, {
      width: rightWidth,
      align: 'right'
    });

  const lineY = y + 60;
  doc
    .moveTo(x, lineY)
    .lineTo(x + PAGE.contentWidth, lineY)
    .lineWidth(2.2)
    .strokeColor(COLORS.brandBlue)
    .stroke();

  doc.y = lineY + 6;
}

function drawTopHeader(doc, mom, authenticity = {}) {
  const x = PAGE.margin;
  const y = 24;
  const rightWidth = 250;

  if (fs.existsSync(LOGO_PATH)) {
    doc.image(LOGO_PATH, x, y, { fit: [230, 58], align: 'left', valign: 'top' });
  } else {
    doc
      .font('Helvetica-Bold')
      .fontSize(18)
      .fillColor(COLORS.brandBlueDark)
      .text('ELEGROW TECHNOLOGY', x, y + 10, { width: 230 });
  }

  doc
    .font('Helvetica')
    .fontSize(8.8)
    .fillColor(COLORS.textMuted)
    .text(`Document ID: ${safeText(authenticity.documentId)}`, x + PAGE.contentWidth - rightWidth, y + 4, {
      width: rightWidth,
      align: 'right'
    })
    .text(`Generated: ${safeText(authenticity.generatedAt)}`, x + PAGE.contentWidth - rightWidth, y + 18, {
      width: rightWidth,
      align: 'right'
    })
    .text(`Generated by: ${safeText(authenticity.generatedBy)}`, x + PAGE.contentWidth - rightWidth, y + 32, {
      width: rightWidth,
      align: 'right'
    });

  const lineY = y + 66;
  doc
    .moveTo(x, lineY)
    .lineTo(x + PAGE.contentWidth, lineY)
    .lineWidth(2.6)
    .strokeColor(COLORS.brandBlue)
    .stroke();

  doc
    .font('Helvetica-Bold')
    .fontSize(22)
    .fillColor(COLORS.brandBlueDark)
    .text('Minutes of Meeting (M.O.M)', x, lineY + 12, {
      width: PAGE.contentWidth,
      align: 'center'
    });

  const cardY = lineY + 58;
  const gap = 10;
  const cardW = (PAGE.contentWidth - gap) / 2;
  const cardH = 42;
  const cards = [
    { label: 'Zoho Project Number', value: normalizeProjectNumber(mom.projectNoWorkOrderNo) },
    { label: 'Owner', value: mom.projectOwner || mom.elegrowRepresentative || '-' }
  ];
  const cardsStartX = x + (PAGE.contentWidth - (cards.length * cardW + (cards.length - 1) * gap)) / 2;

  cards.forEach((card, index) => {
    const cx = cardsStartX + index * (cardW + gap);
    doc
      .roundedRect(cx, cardY, cardW, cardH, 6)
      .lineWidth(1)
      .fillAndStroke(COLORS.brandBlueSoft, COLORS.brandLine);
    doc
      .font('Helvetica-Bold')
      .fontSize(7.9)
      .fillColor(COLORS.textMuted)
      .text(card.label.toUpperCase(), cx + 8, cardY + 6, {
        width: cardW - 16
      });
    doc
      .font('Helvetica-Bold')
      .fontSize(10.8)
      .fillColor(COLORS.brandBlueDark)
      .text(safeText(card.value), cx + 8, cardY + 19, {
        width: cardW - 16,
        ellipsis: true
      });
  });

  doc.y = cardY + cardH + 10;
}

function drawSectionTitle(doc, title, minFollowingHeight = 0, authenticity = null) {
  // Keep section title with at least one block of following content.
  ensurePageSpace(doc, 34 + Math.max(0, minFollowingHeight), authenticity);
  const x = PAGE.margin;
  const y = doc.y;
  doc
    .roundedRect(x, y, PAGE.contentWidth, 24, 6)
    .lineWidth(1)
    .fillAndStroke(COLORS.brandBlueSoft, COLORS.brandLine);
  doc
    .font('Helvetica-Bold')
    .fontSize(11.5)
    .fillColor(COLORS.brandBlueDark)
    .text(title, x + 10, y + 6, {
      width: PAGE.contentWidth - 20
    });
  doc.y = y + 30;
}

function drawTwoColumnRows(doc, rows, authenticity = null) {
  const x = PAGE.margin;
  const width = PAGE.contentWidth;
  const halfWidth = width / 2;
  const labelWidth = 122;
  const pad = 8;

  rows.forEach((row) => {
    const leftValue = safeText(row.leftValue);
    const rightValue = safeText(row.rightValue);

    doc.font('Helvetica').fontSize(10);
    const leftValueHeight = doc.heightOfString(leftValue, {
      width: halfWidth - labelWidth - pad * 2
    });
    const rightValueHeight = doc.heightOfString(rightValue, {
      width: halfWidth - labelWidth - pad * 2
    });
    const rowHeight = Math.max(30, Math.max(leftValueHeight, rightValueHeight) + 14);

    ensurePageSpace(doc, rowHeight + 4, authenticity);

    const y = doc.y;
    doc
      .rect(x, y, width, rowHeight)
      .lineWidth(1)
      .fillAndStroke(COLORS.white, COLORS.brandLine);
    doc
      .moveTo(x + halfWidth, y)
      .lineTo(x + halfWidth, y + rowHeight)
      .lineWidth(1)
      .strokeColor(COLORS.brandLine)
      .stroke();

    doc
      .font('Helvetica-Bold')
      .fontSize(9.5)
      .fillColor(COLORS.brandBlueDark)
      .text(`${row.leftLabel}:`, x + pad, y + 8, {
        width: labelWidth - pad
      });
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(leftValue, x + labelWidth, y + 8, {
        width: halfWidth - labelWidth - pad * 2
      });

    doc
      .font('Helvetica-Bold')
      .fontSize(9.5)
      .fillColor(COLORS.brandBlueDark)
      .text(`${row.rightLabel}:`, x + halfWidth + pad, y + 8, {
        width: labelWidth - pad
      });
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor(COLORS.text)
      .text(rightValue, x + halfWidth + labelWidth, y + 8, {
        width: halfWidth - labelWidth - pad * 2
      });

    doc.y = y + rowHeight;
  });

  doc.moveDown(0.35);
}

function drawStyledTable(doc, title, headers, widths, rows, authenticity = {}) {
  const headerHeight = 24;
  drawSectionTitle(doc, title, headerHeight + 26, authenticity);

  const x = PAGE.margin;
  let y = doc.y;

  const normalizedRows = rows && rows.length ? rows : [headers.map(() => '')];

  function drawHeaderRow(startY) {
    let cx = x;
    headers.forEach((header, index) => {
      const cw = widths[index];
      doc
        .rect(cx, startY, cw, headerHeight)
        .lineWidth(1)
        .fillAndStroke(COLORS.brandBlue, COLORS.brandBlueDark);
      doc
        .font('Helvetica-Bold')
        .fontSize(9)
        .fillColor(COLORS.tableHeaderText)
        .text(header, cx + 6, startY + 7, {
          width: cw - 12,
          align: 'left',
          ellipsis: true
        });
      cx += cw;
    });
  }

  ensurePageSpace(doc, headerHeight + 26, authenticity);
  drawHeaderRow(y);
  y += headerHeight;

  normalizedRows.forEach((rowValues, rowIndex) => {
    const values = rowValues.map((value) => safeText(value));
    doc.font('Helvetica').fontSize(9.2);
    const heights = values.map((value, index) =>
      doc.heightOfString(value, {
        width: widths[index] - 10
      })
    );
    const rowHeight = Math.max(24, Math.max(...heights) + 10);

    if (y + rowHeight > doc.page.height - doc.page.margins.bottom - FOOTER_HEIGHT) {
      doc.addPage();
      drawPageHeader(doc, authenticity);
      y = doc.y;
      drawHeaderRow(y);
      y += headerHeight;
    }

    const rowFill = rowIndex % 2 ? COLORS.rowAlt : COLORS.white;
    let cx = x;
    values.forEach((value, index) => {
      const cw = widths[index];
      doc
        .rect(cx, y, cw, rowHeight)
        .lineWidth(1)
        .fillAndStroke(rowFill, COLORS.brandLine);
      doc
        .font('Helvetica')
        .fontSize(9.2)
        .fillColor(COLORS.text)
        .text(value, cx + 5, y + 6, {
          width: cw - 10
        });
      cx += cw;
    });

    y += rowHeight;
  });

  doc.y = y + 8;
}

function drawPageFooter(doc, mom, authenticity = {}) {
  const x = PAGE.margin;
  const statement = String(authenticity.statement || '').trim() || DIGITAL_DECLARATION_DEFAULT;
  const line = String(authenticity.line || '').trim();
  const y = doc.page.height - doc.page.margins.bottom - FOOTER_HEIGHT + 6;

  doc.save();

  doc
    .roundedRect(x, y, PAGE.contentWidth, FOOTER_HEIGHT - 10, 7)
    .lineWidth(0.9)
    .fillAndStroke(COLORS.blockBg, COLORS.brandLine);

  doc
    .font('Helvetica-Bold')
    .fontSize(8.3)
    .fillColor(COLORS.brandBlueDark)
    .text('DIGITAL RECORD DECLARATION', x + 10, y + 7, {
      width: PAGE.contentWidth - 20
    });

  doc
    .font('Helvetica')
    .fontSize(7.4)
    .fillColor(COLORS.text)
    .text(statement, x + 10, y + 20, {
      width: PAGE.contentWidth - 20,
      height: 18,
      ellipsis: true
    });

  if (line) {
    doc
      .font('Courier')
      .fontSize(7.0)
      .fillColor(COLORS.textMuted)
      .text(line, x + 10, y + 39, {
        width: PAGE.contentWidth - 20,
        height: 10,
        ellipsis: true
      });
  }

  doc
    .moveTo(x, y + FOOTER_HEIGHT - 20)
    .lineTo(x + PAGE.contentWidth, y + FOOTER_HEIGHT - 20)
    .lineWidth(1.2)
    .strokeColor(COLORS.brandBlue)
    .stroke();

  doc
    .font('Helvetica')
    .fontSize(8.1)
    .fillColor(COLORS.textMuted)
    .text(safeText(mom.organizationAddress || DEFAULT_ORG_ADDRESS), x + 8, y + FOOTER_HEIGHT - 16, {
      width: PAGE.contentWidth - 16,
      align: 'center'
    });

  doc.restore();
}

function drawFooterOnAllPages(doc, mom, authenticity = {}) {
  const range = doc.bufferedPageRange();
  const lastPageIndex = range.start + range.count - 1;
  for (let i = range.start; i <= lastPageIndex; i += 1) {
    doc.switchToPage(i);
    drawPageFooter(doc, mom, authenticity);
  }
  doc.switchToPage(lastPageIndex);
}

async function generateMomPdf(mom, outputDir, authenticity = {}) {
  ensureDir(outputDir);

  const fileName = generateFileName();
  const filePath = path.join(outputDir, fileName);

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: PAGE.margin,
      bufferPages: true
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    drawTopHeader(doc, mom, authenticity);

    drawSectionTitle(doc, '1. GENERAL INFORMATION', 40, authenticity);
    drawTwoColumnRows(doc, [
      { leftLabel: 'Meeting Title', leftValue: mom.meetingTitle, rightLabel: 'Project Name', rightValue: mom.projectName },
      {
        leftLabel: 'Zoho Project Number',
        leftValue: normalizeProjectNumber(mom.projectNoWorkOrderNo),
        rightLabel: 'Owner',
        rightValue: mom.projectOwner || mom.elegrowRepresentative
      },
      {
        leftLabel: 'Project No / Work Order No',
        leftValue: mom.projectNoWorkOrderNo,
        rightLabel: 'Client Name',
        rightValue: mom.clientName
      },
      { leftLabel: 'Meeting Date', leftValue: mom.meetingDate, rightLabel: 'Meeting Time', rightValue: mom.meetingTime },
      { leftLabel: 'Entry Time', leftValue: mom.entryTime, rightLabel: 'Exit Time', rightValue: mom.exitTime }
    ], authenticity);

    drawSectionTitle(doc, '2. DETAILS OF MEETING', 40, authenticity);
    drawTwoColumnRows(doc, [
      {
        leftLabel: 'Meeting Location',
        leftValue: mom.meetingLocation,
        rightLabel: 'Meeting Called by',
        rightValue: mom.meetingCalledBy
      },
      {
        leftLabel: 'Type of Meeting',
        leftValue: [...(mom.meetingType || []), mom.meetingTypeOther].filter(Boolean).join(', '),
        rightLabel: 'Project Stage',
        rightValue: mom.projectStatus || '-'
      },
      {
        leftLabel: 'Facilitator Representative',
        leftValue: mom.facilitatorRepresentative,
        rightLabel: 'Elegrow Representative',
        rightValue: mom.elegrowRepresentative
      },
      {
        leftLabel: 'Client Representative',
        leftValue: mom.clientRepresentative,
        rightLabel: 'Zoho Synced On',
        rightValue: mom.projectUpdated || '-'
      }
    ], authenticity);

    drawStyledTable(
      doc,
      '3. AGENDA',
      ['Sr. No', 'Agenda', 'Action Plan', 'Responsibility'],
      [45, 180, 165, 125],
      (mom.agendaRows && mom.agendaRows.length
        ? mom.agendaRows
        : [{ srNo: '1', agenda: '', actionPlan: '', responsibility: '' }]
      ).map((row) => [row.srNo, row.agenda, row.actionPlan, row.responsibility]),
      authenticity
    );

    drawStyledTable(
      doc,
      '4. TASKS',
      ['Sr. No', 'Tasks', 'Quantity / Description', 'Remarks', 'Status'],
      [45, 150, 130, 110, 80],
      (mom.taskRows && mom.taskRows.length
        ? mom.taskRows
        : [{ srNo: '1', taskName: '', quantityDescription: '', remarks: '', status: '' }]
      ).map((row) => [row.srNo, row.taskName || row.taskId || '', row.quantityDescription, row.remarks, row.status]),
      authenticity
    );

    drawStyledTable(
      doc,
      '5. ATTENDEES',
      ['Sr. No', 'Elegrow Technology (Name)', 'Client (Name)'],
      [55, 230, 230],
      (mom.attendeeRows && mom.attendeeRows.length
        ? mom.attendeeRows
        : [{ srNo: '1', elegrowName: '', clientName: '' }]
      ).map((row) => [row.srNo, row.elegrowName, row.clientName]),
      authenticity
    );

    drawFooterOnAllPages(doc, mom, authenticity);

    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return { fileName, filePath };
}

module.exports = {
  generateMomPdf
};
