const path = require('path');
const fs = require('fs');
const express = require('express');

const config = require('./config');
const { getProjects, getProjectUsers, getProjectClientUsers, getProjectTasks } = require('./zohoClient');
const { sanitizeMomPayload, validateMomPayload } = require('./momTemplate');
const { generateMomPdf } = require('./pdfService');
const { createRecordsStore } = require('./recordsStore');

const app = express();
const recordsStore = createRecordsStore(config);
const DIGITAL_DECLARATION_STATEMENT =
  'This Minutes of Meeting (M.O.M) is a digitally generated record of meeting discussions and outcomes. It is produced from system-captured inputs and therefore does not require a handwritten signature for verification.';

function pad2(value) {
  return String(value).padStart(2, '0');
}

function formatAuthTimestamp(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function generateDocumentId(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  const seconds = pad2(date.getSeconds());
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  return `M.O.M-${year}${month}${day}-${hours}${minutes}${seconds}-${randomSuffix}`;
}

function buildAuthenticityMetadata() {
  const generatedAtDate = new Date();
  const generatedAt = formatAuthTimestamp(generatedAtDate);
  const documentId = generateDocumentId(generatedAtDate);
  const generatedBy =
    String(config.app.generatedBy || 'ETPL AI_M.O.M System').trim() || 'ETPL AI_M.O.M System';
  return {
    statement: DIGITAL_DECLARATION_STATEMENT,
    documentId,
    generatedAt,
    generatedBy,
    line: `Document ID: ${documentId} | Generated: ${generatedAt} | Generated by: ${generatedBy}`
  };
}

if (!fs.existsSync(config.app.generatedDir)) {
  fs.mkdirSync(config.app.generatedDir, { recursive: true });
}

function safeUnlinkGeneratedPdf(fileName) {
  const base = path.basename(String(fileName || '').trim());
  if (!base || !base.toLowerCase().endsWith('.pdf')) {
    return;
  }
  const filePath = path.join(config.app.generatedDir, base);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}

function purgeRemovedRecordPdfs(removedRecords = []) {
  for (const record of removedRecords) {
    try {
      safeUnlinkGeneratedPdf(record?.pdfFileName);
    } catch (_error) {
      // No-op: record cleanup should not fail request lifecycle.
    }
  }
}

app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true }));

app.use('/generated-pdfs', express.static(config.app.generatedDir));
app.use(express.static(path.join(config.app.rootDir, 'public')));

function buildAbsolutePdfUrl(pdfUrl) {
  try {
    return new URL(pdfUrl, config.app.baseUrl).toString();
  } catch (_error) {
    return `${String(config.app.baseUrl || '').replace(/\/+$/, '')}${pdfUrl}`;
  }
}

function getProjectRefForEmailSubject(mom) {
  const projectNo = String(mom.projectNoWorkOrderNo || '').trim();
  if (projectNo) {
    return projectNo.split('/')[0].trim() || projectNo;
  }
  const projectName = String(mom.projectName || '').trim();
  return projectName || 'Project';
}

function formatMeetingDateForSubject(rawDate) {
  const value = String(rawDate || '').trim();
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (match) {
    return `${match[1]}/${match[2]}/${match[3]}`;
  }
  return value || new Date().toISOString().slice(0, 10).replace(/-/g, '/');
}

function formatMeetingDateForBody(rawDate) {
  const value = String(rawDate || '').trim();
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (match) {
    const parsed = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
    return parsed.toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });
  }
  const parsed = new Date(value);
  if (!value || Number.isNaN(parsed.getTime())) {
    return value || '-';
  }
  return parsed.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
}

function encodeOutlookQueryComponent(value) {
  return encodeURIComponent(String(value || '')).replace(/[!'()*]/g, (char) => {
    return `%${char.charCodeAt(0).toString(16).toUpperCase()}`;
  });
}

function buildOutlookComposeUrl({ to = '', cc = '', subject = '', body = '' }) {
  const queryParts = [];
  const trimmedTo = String(to || '').trim();
  const trimmedCc = String(cc || '').trim();
  if (trimmedTo) {
    queryParts.push(`to=${encodeOutlookQueryComponent(trimmedTo)}`);
  }
  if (trimmedCc) {
    queryParts.push(`cc=${encodeOutlookQueryComponent(trimmedCc)}`);
  }
  queryParts.push(`subject=${encodeOutlookQueryComponent(subject)}`);
  queryParts.push(`body=${encodeOutlookQueryComponent(body)}`);
  return `https://outlook.office.com/mail/deeplink/compose?${queryParts.join('&')}`;
}

function buildOutlookDraft({ mom, options, pdfUrl }) {
  const to = String(options.emailTo || '').trim();
  const cc = String(options.emailCc || '').trim();
  const projectRef = getProjectRefForEmailSubject(mom);
  const subject =
    String(options.emailSubject || '').trim() ||
    `MOM - Project ${projectRef} - ${formatMeetingDateForSubject(mom.meetingDate)}`;
  const pdfAbsoluteUrl = buildAbsolutePdfUrl(pdfUrl);

  const meetingTitle = String(mom.meetingTitle || '-').trim() || '-';
  const meetingDate = formatMeetingDateForBody(mom.meetingDate);
  const meetingTime = String(mom.meetingTime || '-').trim() || '-';
  const meetingLocation = String(mom.meetingLocation || '-').trim() || '-';

  const defaultBody = [
    'Dear Sir / Madam,',
    '',
    `Please find the Minutes of Meeting (MoM) for the project ${projectRef}, held as per the details below.`,
    '',
    `Project: ${projectRef}`,
    `Meeting Title: ${meetingTitle}`,
    `Meeting Date: ${meetingDate}`,
    `Meeting Time: ${meetingTime}`,
    `Meeting Location: ${meetingLocation}`,
    '',
    'The detailed Minutes of Meeting are attached in the PDF for your reference.',
    'For convenience, you may also access the document using the link below:',
    `${pdfAbsoluteUrl}`,
    '',
    `Open PDF: <${pdfAbsoluteUrl}>`,
    '',
    'Please review the document and feel free to let us know if any clarifications or additions are required.',
    'Best regards,',
    'ETPL_AI MoM System'
  ].join('\n');
  const customBodyRaw = String(options.emailBody || '').trim();
  const customBody = customBodyRaw
    .replace(
      /https?:\/\/[^\s]+\/generated-pdfs\/MOM-<auto-generated>\.pdf/gi,
      pdfAbsoluteUrl
    )
    .replace(/\/generated-pdfs\/MOM-<auto-generated>\.pdf/gi, pdfAbsoluteUrl);
  const body = customBody || defaultBody;

  return {
    mode: 'outlook-draft',
    to,
    cc,
    subject,
    body,
    pdfAbsoluteUrl,
    outlookComposeUrl: buildOutlookComposeUrl({ to, cc, subject, body }),
    attachmentAutoSupported: false,
    attachmentNote:
      'Attachment cannot be auto-added by browser deeplink. The generated PDF is opened for manual attachment.'
  };
}

app.get('/api/health', (_req, res) => {
  const zohoAutoRefreshConfigured = Boolean(
    config.zoho.refreshToken && config.zoho.clientId && config.zoho.clientSecret
  );

  res.json({
    success: true,
    timestamp: new Date().toISOString(),
    zohoMode: config.zoho.useMock ? 'mock' : 'live',
    zohoAutoRefreshConfigured,
    generatedBy: String(config.app.generatedBy || 'ETPL AI_M.O.M System'),
    emailEnabled: true,
    emailMode: 'outlook-draft',
    recordsRetentionDays: recordsStore.settings.retentionDays,
    recordsMaxCount: recordsStore.settings.maxCount
  });
});

app.get('/api/zoho/projects', async (req, res) => {
  try {
    const query = String(req.query.query || '').trim();
    const projects = await getProjects(query);

    res.json({
      success: true,
      projects
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to fetch projects from Zoho Projects'
    });
  }
});

app.get('/api/zoho/projects/:projectId/users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project users for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.get('/api/zoho/projects/:projectId/client-users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectClientUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    res.json({
      success: true,
      users: [],
      message: error.message || 'Zoho client users not available for this project.'
    });
  }
});

app.get('/api/zoho/projects/:projectId/tasks', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const tasks = await getProjectTasks(projectId, {
      query: String(req.query.query || '').trim(),
      status: String(req.query.status || '').trim(),
      index: req.query.index,
      range: req.query.range
    });

    res.json({
      success: true,
      tasks
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project tasks for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.get('/api/mom/records', (req, res) => {
  try {
    const query = String(req.query.query || '').trim();
    const { records, removed } = recordsStore.listRecords(query);
    purgeRemovedRecordPdfs(removed);

    res.json({
      success: true,
      records,
      retentionDays: recordsStore.settings.retentionDays,
      maxCount: recordsStore.settings.maxCount
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to load M.O.M records.'
    });
  }
});

app.delete('/api/mom/records/:recordId', (req, res) => {
  try {
    const recordId = String(req.params.recordId || '').trim();
    const { deleted, record, removed } = recordsStore.deleteRecord(recordId);
    purgeRemovedRecordPdfs(removed);
    if (deleted && record?.pdfFileName) {
      safeUnlinkGeneratedPdf(record.pdfFileName);
    }

    if (!deleted) {
      return res.status(404).json({
        success: false,
        message: 'Record not found.'
      });
    }

    return res.json({
      success: true,
      message: 'Record deleted.',
      deletedRecordId: recordId
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to delete M.O.M record.'
    });
  }
});

app.post('/api/mom/submit', async (req, res) => {
  try {
    const mom = sanitizeMomPayload(req.body.mom || {});
    const options = req.body.options || {};

    const validationErrors = validateMomPayload(mom);
    if (validationErrors.length) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: validationErrors
      });
    }

    const shouldGeneratePdf = Boolean(options.generatePdf || options.printPdf || options.sendEmail);

    if (!shouldGeneratePdf) {
      return res.status(400).json({
        success: false,
        message: 'Select at least one output option (Email, PDF, Print).'
      });
    }

    const authenticity = buildAuthenticityMetadata();
    const { fileName } = await generateMomPdf(mom, config.app.generatedDir, authenticity);
    const pdfUrl = `/generated-pdfs/${fileName}`;

    let emailDraft = null;
    if (options.sendEmail) {
      emailDraft = buildOutlookDraft({
        mom,
        options,
        pdfUrl
      });
    }

    const { record, removed } = recordsStore.addRecord({
      documentId: authenticity.documentId,
      meetingTitle: mom.meetingTitle,
      projectName: mom.projectName,
      projectNoWorkOrderNo: mom.projectNoWorkOrderNo,
      clientName: mom.clientName,
      meetingDate: mom.meetingDate,
      meetingTime: mom.meetingTime,
      meetingLocation: mom.meetingLocation,
      output: {
        generatePdf: Boolean(options.generatePdf),
        printPdf: Boolean(options.printPdf),
        sendEmail: Boolean(options.sendEmail)
      },
      pdfUrl,
      pdfFileName: fileName,
      pdfAbsoluteUrl: buildAbsolutePdfUrl(pdfUrl)
    });
    purgeRemovedRecordPdfs(removed);

    return res.json({
      success: true,
      message: 'M.O.M processed successfully.',
      result: {
        pdfUrl,
        pdfFileName: fileName,
        pdfAbsoluteUrl: buildAbsolutePdfUrl(pdfUrl),
        authenticity,
        emailSent: false,
        emailDraft,
        printRequested: Boolean(options.printPdf),
        record
      }
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to process M.O.M submission'
    });
  }
});

app.get('*', (_req, res) => {
  res.sendFile(path.join(config.app.rootDir, 'public', 'index.html'));
});

const server = app.listen(config.app.port, config.app.host, () => {
  // eslint-disable-next-line no-console
  console.log(`M.O.M app running at ${config.app.baseUrl} on port ${config.app.port}`);
});

server.on('error', (error) => {
  // eslint-disable-next-line no-console
  console.error(`Server startup failed: ${error.code || error.message}`);
  process.exit(1);
});
