const path = require('path');
const fs = require('fs');
const express = require('express');
const multer = require('multer');

const config = require('./config');
const {
  getProjects,
  getProjectUsers,
  getProjectClientUsers,
  getProjectTasks,
  postTaskComment,
  attachFileToTask,
  runZohoDiagnostics
} = require('./zohoClient');
const { sanitizeMomPayload, validateMomPayload } = require('./momTemplate');
const { generateMomPdf } = require('./pdfService');
const { createRecordsStore } = require('./recordsStore');
const {
  isGraphDraftConfigured,
  buildGraphBodyHtml,
  createGraphDraft,
  runGraphDiagnostics
} = require('./graphMailService');
const { scanMeetingDocumentWithGemini } = require('./geminiAssistant');

const app = express();
const recordsStore = createRecordsStore(config);
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: config.gemini.maxUploadBytes
  }
});
const DIGITAL_DECLARATION_STATEMENT =
  'This Minutes of Meeting (M.O.M) is a digitally generated record of meeting discussions and outcomes. It is produced from system-captured inputs and therefore does not require a handwritten signature for verification.';

function pad2(value) {
  return String(value).padStart(2, '0');
}

function formatAuthTimestamp(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function generateDocumentId(date) {
  const year = date.getFullYear();
  const month = pad2(date.getMonth() + 1);
  const day = pad2(date.getDate());
  const hours = pad2(date.getHours());
  const minutes = pad2(date.getMinutes());
  const seconds = pad2(date.getSeconds());
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  return `M.O.M-${year}${month}${day}-${hours}${minutes}${seconds}-${randomSuffix}`;
}

function buildAuthenticityMetadata() {
  const generatedAtDate = new Date();
  const generatedAt = formatAuthTimestamp(generatedAtDate);
  const documentId = generateDocumentId(generatedAtDate);
  const generatedBy =
    String(config.app.generatedBy || 'ETPL_AI M.O.M System').trim() || 'ETPL_AI M.O.M System';
  return {
    statement: DIGITAL_DECLARATION_STATEMENT,
    documentId,
    generatedAt,
    generatedBy,
    line: `Document ID: ${documentId} | Generated: ${generatedAt} | Generated by: ${generatedBy}`
  };
}

if (!fs.existsSync(config.app.generatedDir)) {
  fs.mkdirSync(config.app.generatedDir, { recursive: true });
}

function safeUnlinkGeneratedPdf(fileName) {
  const base = path.basename(String(fileName || '').trim());
  if (!base || !base.toLowerCase().endsWith('.pdf')) {
    return;
  }
  const filePath = path.join(config.app.generatedDir, base);
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
  }
}

function purgeRemovedRecordPdfs(removedRecords = []) {
  for (const record of removedRecords) {
    try {
      safeUnlinkGeneratedPdf(record?.pdfFileName);
    } catch (_error) {
      // No-op: record cleanup should not fail request lifecycle.
    }
  }
}

app.use(express.json({ limit: '5mb' }));
app.use(express.urlencoded({ extended: true }));

app.use('/generated-pdfs', express.static(config.app.generatedDir));
app.use(express.static(path.join(config.app.rootDir, 'public')));

function normalizePublicBaseUrl(baseUrl) {
  const value = String(baseUrl || '').trim();
  if (!value) {
    return value;
  }

  try {
    const url = new URL(value);
    if (url.hostname === 'mom.elegrow.com') {
      url.hostname = 'www.mom.elegrow.com';
    }
    return url.toString().replace(/\/+$/, '');
  } catch (_error) {
    return value.replace(/^https?:\/\/mom\.elegrow\.com/i, 'https://www.mom.elegrow.com').replace(/\/+$/, '');
  }
}

function getRequestBaseUrl(req) {
  const forwardedProto = String(req.headers['x-forwarded-proto'] || '').split(',')[0].trim();
  const forwardedHost = String(req.headers['x-forwarded-host'] || '').split(',')[0].trim();
  const host = forwardedHost || String(req.get('host') || '').trim();
  const proto = forwardedProto || req.protocol || 'https';

  if (host) {
    return normalizePublicBaseUrl(`${proto}://${host}`);
  }

  return normalizePublicBaseUrl(config.app.baseUrl);
}

function buildAbsolutePdfUrl(pdfUrl, req = null) {
  const baseUrl = req ? getRequestBaseUrl(req) : normalizePublicBaseUrl(config.app.baseUrl);
  try {
    return new URL(pdfUrl, baseUrl).toString();
  } catch (_error) {
    return `${String(baseUrl || '').replace(/\/+$/, '')}${pdfUrl}`;
  }
}

function getProjectRefForEmailSubject(mom) {
  const projectNo = String(mom.projectNoWorkOrderNo || '').trim();
  if (projectNo) {
    return projectNo.split('/')[0].trim() || projectNo;
  }
  const projectName = String(mom.projectName || '').trim();
  return projectName || 'Project';
}

function getZohoCommentTargetTasks(mom) {
  const rows = Array.isArray(mom?.taskRows) ? mom.taskRows : [];
  return rows
    .map((row, index) => ({
      index,
      srNo: String(row?.srNo || index + 1).trim(),
      taskId: String(row?.taskId || '').trim(),
      taskName: String(row?.taskName || '').trim(),
      quantityDescription: String(row?.quantityDescription || '').trim(),
      remarks: String(row?.remarks || '').trim(),
      status: String(row?.status || '').trim()
    }))
    .filter((row) => row.taskId);
}

function buildZohoTaskCommentBody({ mom, pdfAbsoluteUrl, authenticity, task }) {
  const lines = [
    'Minutes of Meeting (M.O.M) generated from ETPL_AI M.O.M System.',
    '',
    `Document ID: ${String(authenticity?.documentId || '').trim() || '-'}`,
    `Project: ${String(mom.projectNoWorkOrderNo || mom.projectName || '').trim() || '-'}`,
    `Task: ${String(task?.taskName || task?.taskId || '').trim() || '-'}`,
    `Meeting Title: ${String(mom.meetingTitle || '').trim() || '-'}`,
    `Meeting Date: ${String(mom.meetingDate || '').trim() || '-'}`,
    `Meeting Time: ${String(mom.meetingTime || '').trim() || '-'}`,
    `Meeting Location: ${String(mom.meetingLocation || '').trim() || '-'}`,
    '',
    'M.O.M PDF Link:',
    String(pdfAbsoluteUrl || '').trim(),
    '',
    'Please review the linked M.O.M document for complete details.'
  ];

  if (String(task?.quantityDescription || '').trim()) {
    lines.splice(8, 0, `Task Notes: ${String(task.quantityDescription).trim()}`);
  }
  if (String(task?.remarks || '').trim()) {
    lines.splice(9, 0, `Remarks: ${String(task.remarks).trim()}`);
  }
  if (String(task?.status || '').trim()) {
    lines.splice(10, 0, `M.O.M Task Status: ${String(task.status).trim()}`);
  }

  return lines.join('\n');
}

async function syncMomLinkToZohoTasks({ mom, pdfAbsoluteUrl, authenticity }) {
  const projectSource = String(mom?.projectSource || '').trim().toLowerCase();
  if (projectSource !== 'zoho') {
    return {
      attempted: false,
      syncedTasks: [],
      skippedReason: 'Project source is not Zoho.'
    };
  }

  const zohoProjectId = String(mom?.zohoProjectId || '').trim();
  if (!zohoProjectId) {
    throw new Error('Zoho project ID is missing. Please re-select the Zoho project before submitting.');
  }

  const targetTasks = getZohoCommentTargetTasks(mom);
  if (!targetTasks.length) {
    throw new Error(
      'At least one Zoho task must be selected in the Tasks section. The M.O.M link is posted automatically to selected Zoho tasks.'
    );
  }

  const syncedTasks = [];
  for (const task of targetTasks) {
    const content = buildZohoTaskCommentBody({ mom, pdfAbsoluteUrl, authenticity, task });
    const comment = await postTaskComment(zohoProjectId, task.taskId, content);
    syncedTasks.push({
      taskId: task.taskId,
      taskName: task.taskName,
      srNo: task.srNo,
      commentId: String(comment?.id || '').trim(),
      syncedAt: new Date().toISOString(),
      status: 'comment_posted'
    });
  }

  return {
    attempted: true,
    syncedTasks
  };
}

function formatMeetingDateForSubject(rawDate) {
  const value = String(rawDate || '').trim();
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (match) {
    return `${match[1]}/${match[2]}/${match[3]}`;
  }
  return value || new Date().toISOString().slice(0, 10).replace(/-/g, '/');
}

function formatMeetingDateForBody(rawDate) {
  const value = String(rawDate || '').trim();
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (match) {
    const parsed = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
    return parsed.toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    });
  }
  const parsed = new Date(value);
  if (!value || Number.isNaN(parsed.getTime())) {
    return value || '-';
  }
  return parsed.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
}

function encodeOutlookQueryComponent(value) {
  return encodeURIComponent(String(value || '')).replace(/[!'()*]/g, (char) => {
    return `%${char.charCodeAt(0).toString(16).toUpperCase()}`;
  });
}

function buildOutlookComposeUrlDesktop({ to = '', cc = '', subject = '', body = '' }) {
  const queryParts = [];
  const trimmedTo = String(to || '').trim();
  const trimmedCc = String(cc || '').trim();
  if (trimmedTo) {
    queryParts.push(`to=${encodeOutlookQueryComponent(trimmedTo)}`);
  }
  if (trimmedCc) {
    queryParts.push(`cc=${encodeOutlookQueryComponent(trimmedCc)}`);
  }
  queryParts.push(`subject=${encodeOutlookQueryComponent(subject)}`);
  queryParts.push(`body=${encodeOutlookQueryComponent(body)}`);
  return `https://outlook.office.com/mail/deeplink/compose?${queryParts.join('&')}`;
}

function buildOutlookComposeUrlMobile({ to = '', cc = '', subject = '', body = '' }) {
  // Use deep-link compose endpoint for mobile too; /mail/?rru=compose is unreliable on iOS.
  return buildOutlookComposeUrlDesktop({ to, cc, subject, body });
}

function buildOutlookAppComposeUrl({ to = '', cc = '', subject = '', body = '' }) {
  const queryParts = [];
  const trimmedTo = String(to || '').trim();
  const trimmedCc = String(cc || '').trim();
  if (trimmedTo) {
    queryParts.push(`to=${encodeOutlookQueryComponent(trimmedTo)}`);
  }
  if (trimmedCc) {
    queryParts.push(`cc=${encodeOutlookQueryComponent(trimmedCc)}`);
  }
  queryParts.push(`subject=${encodeOutlookQueryComponent(subject)}`);
  return `ms-outlook://compose?${queryParts.join('&')}`;
}

function buildEmailDraftPayload({ mom, options, pdfUrl, pdfFileName = '', req = null }) {
  const to = String(options.emailTo || '').trim();
  const cc = String(options.emailCc || '').trim();
  const projectRef = getProjectRefForEmailSubject(mom);
  const subject =
    String(options.emailSubject || '').trim() ||
    `MOM - Project ${projectRef} - ${formatMeetingDateForSubject(mom.meetingDate)}`;
  const pdfAbsoluteUrl = buildAbsolutePdfUrl(pdfUrl, req);
  const pdfFilePath = pdfFileName ? path.join(config.app.generatedDir, pdfFileName) : '';

  const meetingTitle = String(mom.meetingTitle || '-').trim() || '-';
  const meetingDate = formatMeetingDateForBody(mom.meetingDate);
  const meetingTime = String(mom.meetingTime || '-').trim() || '-';
  const meetingLocation = String(mom.meetingLocation || '-').trim() || '-';

  const bodyText = [
    'Dear Sir / Madam,',
    '',
    `Please find the Minutes of Meeting (MoM) for the project ${projectRef}, held as per the details below.`,
    '',
    `Project: ${projectRef}`,
    `Meeting Title: ${meetingTitle}`,
    `Meeting Date: ${meetingDate}`,
    `Meeting Time: ${meetingTime}`,
    `Meeting Location: ${meetingLocation}`,
    '',
    'The detailed Minutes of Meeting are attached in the PDF for your reference.',
    'For convenience, you may also access the document using the link below:',
    `${pdfAbsoluteUrl}`,
    '',
    'Please review the document and feel free to let us know if any clarifications or additions are required.',
    'Best regards,',
    'ETPL_AI MoM System'
  ].join('\r\n');
  // Keep compose body aligned with the official professional format requested by user.
  const composeBodyText = bodyText;
  const bodyHtml = buildGraphBodyHtml({
    bodyText,
    pdfUrl: pdfAbsoluteUrl
  });

  return {
    to,
    cc,
    subject,
    bodyText,
    composeBodyText,
    bodyHtml,
    pdfAbsoluteUrl,
    pdfFileName: String(pdfFileName || '').trim(),
    pdfFilePath,
    projectRef
  };
}

function buildOutlookDraftFromPayload(payload, warning = '') {
  const to = String(payload.to || '').trim();
  const cc = String(payload.cc || '').trim();
  const subject = String(payload.subject || '').trim();
  const body = String(payload.composeBodyText || payload.bodyText || '').trim();
  return {
    mode: 'outlook-draft',
    to,
    cc,
    subject,
    body,
    projectRef: payload.projectRef,
    pdfAbsoluteUrl: payload.pdfAbsoluteUrl,
    outlookComposeUrl: buildOutlookComposeUrlDesktop({ to, cc, subject, body }),
    outlookComposeMobileUrl: buildOutlookComposeUrlMobile({ to, cc, subject, body }),
    outlookAppComposeUrl: buildOutlookAppComposeUrl({ to, cc, subject, body }),
    attachmentAutoSupported: false,
    attachmentNote:
      warning ||
      'Attachment cannot be auto-added by browser deeplink. The generated PDF is opened for manual attachment.'
  };
}

async function buildEmailDraft({ mom, options, pdfUrl, pdfFileName = '', req = null }) {
  const payload = buildEmailDraftPayload({
    mom,
    options,
    pdfUrl,
    pdfFileName,
    req
  });

  if (!isGraphDraftConfigured(config)) {
    return buildOutlookDraftFromPayload(payload);
  }

  try {
    const graphDraft = await createGraphDraft(config, {
      to: payload.to,
      cc: payload.cc,
      subject: payload.subject,
      bodyText: payload.bodyText,
      bodyHtml: payload.bodyHtml,
      pdfFileName: payload.pdfFileName,
      pdfFilePath: payload.pdfFilePath
    });

    return {
      ...graphDraft,
      to: payload.to,
      cc: payload.cc,
      subject: payload.subject,
      body: payload.bodyText,
      projectRef: payload.projectRef,
      pdfAbsoluteUrl: payload.pdfAbsoluteUrl,
      graphMailboxUser: String(config.graph.mailboxUser || '').trim(),
      openGraphWebLink: Boolean(config.graph.openGraphWebLink),
      // Keep deeplink URLs as hard fallback.
      outlookComposeUrl: buildOutlookComposeUrlDesktop({
        to: payload.to,
        cc: payload.cc,
        subject: payload.subject,
        body: payload.composeBodyText
      }),
      outlookComposeMobileUrl: buildOutlookComposeUrlMobile({
        to: payload.to,
        cc: payload.cc,
        subject: payload.subject,
        body: payload.composeBodyText
      }),
      outlookAppComposeUrl: buildOutlookAppComposeUrl({
        to: payload.to,
        cc: payload.cc,
        subject: payload.subject,
        body: payload.composeBodyText
      })
    };
  } catch (error) {
    // Log full error server-side, but keep user-facing fallback message concise.
    // eslint-disable-next-line no-console
    console.error(`Graph draft creation failed: ${error.message}`);
    return buildOutlookDraftFromPayload(
      payload,
      `Microsoft Graph draft is unavailable right now (${error.message}). Switched to Outlook deeplink fallback.`
    );
  }
}

function buildRecordMomShape(record) {
  return {
    meetingTitle: String(record?.meetingTitle || '').trim(),
    projectName: String(record?.projectName || '').trim(),
    projectNoWorkOrderNo: String(record?.projectNoWorkOrderNo || '').trim(),
    meetingDate: String(record?.meetingDate || '').trim(),
    meetingTime: String(record?.meetingTime || '').trim(),
    meetingLocation: String(record?.meetingLocation || '').trim()
  };
}

function getRecordById(recordId) {
  const { records, removed } = recordsStore.listRecords('');
  purgeRemovedRecordPdfs(removed);
  const targetId = String(recordId || '').trim();
  return (Array.isArray(records) ? records.find((item) => String(item.id || '') === targetId) : null) || null;
}

async function attachRecordPdfToZohoTasks(record) {
  if (!record) {
    throw new Error('Record not found.');
  }

  const projectSource = String(record.projectSource || '').trim().toLowerCase();
  if (projectSource !== 'zoho') {
    throw new Error('This record is not linked to a Zoho project.');
  }

  const zohoProjectId = String(record.zohoProjectId || '').trim();
  if (!zohoProjectId) {
    throw new Error('Zoho project ID is missing on this record.');
  }

  const pdfFileName = path.basename(String(record.pdfFileName || '').trim());
  if (!pdfFileName) {
    throw new Error('Generated PDF file name is missing on this record.');
  }

  const pdfFilePath = path.join(config.app.generatedDir, pdfFileName);
  if (!fs.existsSync(pdfFilePath)) {
    throw new Error('Generated PDF file could not be found on the server.');
  }

  const targetTasks = getZohoCommentTargetTasks({
    taskRows: Array.isArray(record.taskRows) ? record.taskRows : []
  });
  if (!targetTasks.length) {
    throw new Error('No Zoho tasks are associated with this record.');
  }

  const attachedTasks = [];
  for (const task of targetTasks) {
    const attachment = await attachFileToTask(zohoProjectId, task.taskId, pdfFilePath, pdfFileName);
    attachedTasks.push({
      srNo: task.srNo,
      taskId: task.taskId,
      taskName: task.taskName,
      attachmentId: attachment.id,
      fileName: attachment.fileName
    });
  }

  return {
    attempted: true,
    attachedTasks
  };
}

app.get('/api/health', (_req, res) => {
  const zohoAutoRefreshConfigured = Boolean(
    config.zoho.refreshToken && config.zoho.clientId && config.zoho.clientSecret
  );
  const graphDraftConfigured = isGraphDraftConfigured(config);

  res.json({
    success: true,
    timestamp: new Date().toISOString(),
    zohoMode: config.zoho.useMock ? 'mock' : 'live',
    zohoAutoRefreshConfigured,
    graphDraftConfigured,
    generatedBy: String(config.app.generatedBy || 'ETPL_AI M.O.M System'),
    emailEnabled: true,
    emailMode: graphDraftConfigured ? 'graph-draft' : 'outlook-draft',
    recordsRetentionDays: recordsStore.settings.retentionDays,
    recordsMaxCount: recordsStore.settings.maxCount
  });
});

app.get('/api/graph/diagnostics', async (req, res) => {
  const writeProbe = String(req.query.writeProbe || '').toLowerCase() === 'true';
  try {
    const diagnostics = await runGraphDiagnostics(config, { writeProbe });
    res.json({
      success: true,
      diagnostics
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Graph diagnostics failed.'
    });
  }
});

app.get('/api/zoho/diagnostics', async (req, res) => {
  const writeProbe = String(req.query.writeProbe || '').toLowerCase() === 'true';
  const projectId = String(req.query.projectId || '').trim();
  const taskId = String(req.query.taskId || '').trim();

  try {
    const diagnostics = await runZohoDiagnostics({
      writeProbe,
      projectId,
      taskId
    });

    res.json({
      success: true,
      diagnostics
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Zoho diagnostics failed.'
    });
  }
});

app.get('/api/zoho/projects', async (req, res) => {
  try {
    const query = String(req.query.query || '').trim();
    const projects = await getProjects(query);

    res.json({
      success: true,
      projects
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to fetch projects from Zoho Projects'
    });
  }
});

app.get('/api/zoho/projects/:projectId/users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project users for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.get('/api/zoho/projects/:projectId/client-users', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const users = await getProjectClientUsers(projectId);

    res.json({
      success: true,
      users
    });
  } catch (error) {
    res.json({
      success: true,
      users: [],
      message: error.message || 'Zoho client users not available for this project.'
    });
  }
});

app.get('/api/zoho/projects/:projectId/tasks', async (req, res) => {
  try {
    const projectId = String(req.params.projectId || '').trim();
    const tasks = await getProjectTasks(projectId, {
      query: String(req.query.query || '').trim(),
      status: String(req.query.status || '').trim(),
      index: req.query.index,
      range: req.query.range
    });

    res.json({
      success: true,
      tasks
    });
  } catch (error) {
    const projectId = String(req.params.projectId || '').trim();
    res.status(500).json({
      success: false,
      message:
        error.message || `Failed to fetch Zoho project tasks for project ID: ${projectId || '(empty)'}`
    });
  }
});

app.get('/api/mom/records', (req, res) => {
  try {
    const query = String(req.query.query || '').trim();
    const { records, removed } = recordsStore.listRecords(query);
    purgeRemovedRecordPdfs(removed);

    res.json({
      success: true,
      records,
      retentionDays: recordsStore.settings.retentionDays,
      maxCount: recordsStore.settings.maxCount
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to load M.O.M records.'
    });
  }
});

app.post('/upload', upload.single('document'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: 'Please choose a document to scan.'
      });
    }

    const extracted = await scanMeetingDocumentWithGemini(config, req.file);

    return res.json({
      success: true,
      agenda: extracted.agenda,
      discussion: extracted.discussion,
      action_items: extracted.action_items
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to scan meeting document.'
    });
  }
});

app.post('/api/upload', upload.single('document'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: 'Please choose a document to scan.'
      });
    }

    const extracted = await scanMeetingDocumentWithGemini(config, req.file);

    return res.json({
      success: true,
      agenda: extracted.agenda,
      discussion: extracted.discussion,
      action_items: extracted.action_items
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to scan meeting document.'
    });
  }
});

app.delete('/api/mom/records/:recordId', (req, res) => {
  try {
    const recordId = String(req.params.recordId || '').trim();
    const { deleted, record, removed } = recordsStore.deleteRecord(recordId);
    purgeRemovedRecordPdfs(removed);
    if (deleted && record?.pdfFileName) {
      safeUnlinkGeneratedPdf(record.pdfFileName);
    }

    if (!deleted) {
      return res.status(404).json({
        success: false,
        message: 'Record not found.'
      });
    }

    return res.json({
      success: true,
      message: 'Record deleted.',
      deletedRecordId: recordId
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to delete M.O.M record.'
    });
  }
});

app.use((error, _req, res, next) => {
  if (error instanceof multer.MulterError) {
    if (error.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({
        success: false,
        message: `File is too large. Maximum allowed size is ${Math.round(config.gemini.maxUploadBytes / (1024 * 1024))} MB.`
      });
    }

    return res.status(400).json({
      success: false,
      message: error.message || 'Upload failed.'
    });
  }

  return next(error);
});

app.post('/api/mom/records/:recordId/email-draft', async (req, res) => {
  try {
    const recordId = String(req.params.recordId || '').trim();
    const record = getRecordById(recordId);
    if (!record) {
      return res.status(404).json({
        success: false,
        message: 'Record not found.'
      });
    }

    const options = req.body.options || {};
    if (!options.sendEmail) {
      return res.status(400).json({
        success: false,
        message: 'Email export option is required.'
      });
    }

    const pdfUrl = String(record.pdfUrl || '').trim();
    if (!pdfUrl) {
      return res.status(400).json({
        success: false,
        message: 'PDF URL is unavailable for this record.'
      });
    }

    const emailDraft = await buildEmailDraft({
      mom: buildRecordMomShape(record),
      options,
      pdfUrl,
      pdfFileName: String(record.pdfFileName || '').trim(),
      req
    });

    return res.json({
      success: true,
      emailDraft
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to build email draft for record.'
    });
  }
});

app.post('/api/mom/records/:recordId/zoho-attach-pdf', async (req, res) => {
  try {
    const recordId = String(req.params.recordId || '').trim();
    const record = getRecordById(recordId);
    if (!record) {
      return res.status(404).json({
        success: false,
        message: 'Record not found.'
      });
    }

    const zohoTaskAttachmentSync = await attachRecordPdfToZohoTasks(record);

    const { record: updatedRecord } = recordsStore.updateRecord(record.id, {
      zohoTaskAttachmentSync: zohoTaskAttachmentSync.attachedTasks
    });

    return res.json({
      success: true,
      message: 'M.O.M PDF attached to Zoho task(s) successfully.',
      zohoTaskAttachmentSync,
      record: updatedRecord || record
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to attach PDF to Zoho task(s).'
    });
  }
});

app.post('/api/mom/submit', async (req, res) => {
  try {
    const mom = sanitizeMomPayload(req.body.mom || {});
    const options = req.body.options || {};

    const validationErrors = validateMomPayload(mom);
    if (validationErrors.length) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: validationErrors
      });
    }

    const shouldGeneratePdf = Boolean(options.generatePdf || options.printPdf || options.sendEmail);

    if (!shouldGeneratePdf) {
      return res.status(400).json({
        success: false,
        message: 'Select at least one output option (Email, PDF, Print).'
      });
    }

    if (String(mom.projectSource || '').trim().toLowerCase() === 'zoho') {
      if (!String(mom.zohoProjectId || '').trim()) {
        return res.status(400).json({
          success: false,
          message: 'Zoho project is missing. Please re-select the Zoho project before submitting.'
        });
      }

      if (!getZohoCommentTargetTasks(mom).length) {
        return res.status(400).json({
          success: false,
          message:
            'At least one Zoho task must be selected in the Tasks section. The M.O.M link is posted automatically to selected Zoho tasks.'
        });
      }
    }

    const authenticity = buildAuthenticityMetadata();
    const { fileName } = await generateMomPdf(mom, config.app.generatedDir, authenticity);
    const pdfUrl = `/generated-pdfs/${fileName}`;
    const pdfAbsoluteUrl = buildAbsolutePdfUrl(pdfUrl, req);

    const zohoTaskCommentSync = await syncMomLinkToZohoTasks({
      mom,
      pdfAbsoluteUrl,
      authenticity
    });

    let emailDraft = null;
    if (options.sendEmail) {
      emailDraft = await buildEmailDraft({
        mom,
        options,
        pdfUrl,
        pdfFileName: fileName,
        req
      });
    }

    const { record, removed } = recordsStore.addRecord({
      documentId: authenticity.documentId,
      meetingTitle: mom.meetingTitle,
      projectName: mom.projectName,
      projectNoWorkOrderNo: mom.projectNoWorkOrderNo,
      clientName: mom.clientName,
      meetingDate: mom.meetingDate,
      meetingTime: mom.meetingTime,
      meetingLocation: mom.meetingLocation,
      projectSource: mom.projectSource,
      zohoProjectId: mom.zohoProjectId,
      taskRows: mom.taskRows,
      zohoTaskCommentSync: zohoTaskCommentSync.syncedTasks,
      output: {
        generatePdf: Boolean(options.generatePdf),
        printPdf: Boolean(options.printPdf),
        sendEmail: Boolean(options.sendEmail)
      },
      pdfUrl,
      pdfFileName: fileName,
      pdfAbsoluteUrl
    });
    purgeRemovedRecordPdfs(removed);

    return res.json({
      success: true,
      message: 'M.O.M processed successfully.',
      result: {
        pdfUrl,
        pdfFileName: fileName,
        pdfAbsoluteUrl,
        authenticity,
        emailSent: false,
        emailDraft,
        printRequested: Boolean(options.printPdf),
        zohoTaskCommentSync,
        record
      }
    });
  } catch (error) {
    return res.status(500).json({
      success: false,
      message: error.message || 'Failed to process M.O.M submission'
    });
  }
});

app.get('*', (_req, res) => {
  res.sendFile(path.join(config.app.rootDir, 'public', 'index.html'));
});

const server = app.listen(config.app.port, config.app.host, () => {
  // eslint-disable-next-line no-console
  console.log(`M.O.M app running at ${config.app.baseUrl} on port ${config.app.port}`);
});

server.on('error', (error) => {
  // eslint-disable-next-line no-console
  console.error(`Server startup failed: ${error.code || error.message}`);
  process.exit(1);
});
